name: ci
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  automated-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["8.3"]
    env:
      PHP_VERSION: ${{ matrix.php_version }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Modify web container version
        run: sed -i 's/httpd-php:8\.3-\(dev\|ci\)/httpd-php:${{ matrix.php_version}}-ci/g' docker-compose.yml

      - name: Start services with Docker Compose
        run: docker compose up -d

      - name: Build dependencies
        run: docker compose exec -T web composer install

      - name: Run grumphp
        run: docker compose exec -T web ./vendor/bin/grumphp run

      - name: Run tests
        run: docker compose exec -T web ./vendor/bin/phpunit
